version: '3.9'
services:
  mysql:
    container_name: dev-shared-mysql
    image: mysql:8.0.25
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER:          admin
      MYSQL_PASSWORD:      12345678
    volumes:
      - "dev_db:/var/lib/mysql"
    networks:
      - dev-shared
  redis:
    image: redis:5.0.5-alpine
    container_name: dev-shared-redis
    restart: always
    environment:
      - "ENV=develop"
    ports:
      - "8702:6379"
    expose:
      - "6379"
    networks:
      - dev-shared
  phpmyadmin:
    container_name: dev-shared-pma
    image: phpmyadmin/phpmyadmin
    ports:
     - "8008:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - dev-shared
    depends_on:
      - mysql

networks:
  dev-shared: 
    external:
      name: dev-shared
volumes:
  dev_db:
    external: true
